name: popup-direct
region: fra
services:
  - name: web
    github:
      repo: VOTRE-USER/VOTRE-REPO
      branch: master
      deploy_on_push: true
    build_command: npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /health
      initial_delay_seconds: 20
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: CLOAKING_ENABLED
        value: "true"
      - key: REFERER_CLOAKING_ENABLED
        value: "false"
      - key: PORT
        value: "8080"
